---
title: "Introduction to DSGE Modelling"
subtitle: "FSSR-MRD Teach-in"
author: "Harry Li"
institute: "Bank of England"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: ["mtheme.css", "fonts_mtheme.css", "hygge", "default"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

```{r setup, echo=FALSE}
xaringanExtra::use_tile_view()
xaringanExtra::use_scribble()
xaringanExtra::use_panelset()
```

# Introduction

**Dynamic Stochastic General Equilibrium (DSGE)**:
- *Dynamic* - Inter-temporal problems and agents rationally form expectations
- *Stochastic* -  Allow for exogenous stochastic processes such as random shocks
- *General Equilibrium* - Agents are utility maximising and markets are in equilibrium

### Motivation
- Popular in macroeconomics research
- Explaining historical time-series data and for forecasting
- Widely used by Central Banks

### Aim
- Introduction to DSGE Modelling
- Derive simple DSGE models analytically

### Prerequisites
- Method of Lagrange multipliers useful but not essential

???
### Definition
DSGE stands for Dynamic Stochastic General Equilibrium. Break down definition.

### Motivation
- DSGE models are widely used in macroeconomic research and appear in almost every substantive area of macroeconomics, such as the theory of investment, the theory of the consumer, search theory, public finance, growth theory and so on. One of the reasons that DSGE models are attractive is that these models are derived from micro foundations - that is households with rational expectations maximizing utility, firms maximize profits, in general equilibrium. 

DSGE models can be used to explain and predict co-movements of aggregate time series over the business cycle as well as to perform policy analysis. DSGE models are also a prominent tool for forecasting - almost every central bank has some DSGE model, such as the Bank of England's COMPASS. Therefore, it's useful to understand how these models work.

### Aim
The aim of this teach-in is to give an introduction to DSGE modelling. At the end of this teach-in, you should be able to derive simple DSGE models analytically. Technical mathematical details are omitted, but useful resources are provided at the end for further reading. 

### Prerequisites
No prerequisites are required but some basic knowledge of convex optimisation, in particular the method of Lagrangian multipliers is useful.
---

# Overview of DSGE model structures

.pull-left[.Large[Discrete Time]
- $t = \{0, 1, 2, ... \}$
- Simpler
- Bellman equation
]

.pull-right[.Large[Continuous Time]
- $t \in \mathbb{R}$
- More analytical tractability
- Hamilton-Jacobi-Bellman equation
]

.pull-left[.Large[Homogeneous Agents]
- Households/firms' preferences identical
- Assumption often not realistic
- Answer aggregate questions
]

.pull-right[.Large[Heterogeneous Agents]
- Households/firms' preferences differ
- Empirically matches data better
- Answer distributional questions
]


.pull-left[.Large[Infinite Horizon]
- Agents live indefinitely
- Stationary
]

.pull-right[.Large[Finite Horizon]
- Agents live for a finite amount of time
- Non-stationary
]


???
### Overview
There are many types of DSGE model structures and I'll talk briefly about some of these structures and their relative advantages and disadvantages. The methods required for solving these models differ. Given this is an introductory teach-in, I will focus only on methods to solve discrete time models with homogeneous household structure. I'll cover methods for solving both infinite horizon and finite horizon problems, given that they are very similar. 

### Modelling with Discrete Time or Continuous Time 

To start with, time may be modelled as discrete or continuous. In discrete time models, values of variables can change only at distinct points in time, whereas in continuous time models, values of variables may change in an infinitesimally short amount of time.

The advantage of discrete time models is that they are often simpler and more intuitive. However, continuous time models have more analytical tractability - since variables have the nice property of being differentiable.

The method for solving discrete time models recursively is by solving a Bellman equation - which will be discussed in this teach-in. The method for solving continuous time models recursively is by solving a Hamilton-Jacobi-Bellman equation. Given this is an introductory course, I won't be covering this, but I've left some useful resources at the end for further reading.

### Modelling with homogeneous agents or heterogeneous agents
Another model consideration is whether to have homogeneous or heterogeneous agents. For example, if you had a model with homogeneous households, this just means that household preferences are identical, whereas a model with heterogeneous households can allow for differences in household preferences.

The advantage of homogeneous-agent models is that they are simpler. However, this assumption many not be realistic while heterogeneous-agent models can better match the data. Nevertheless, homogeneous-agent models aren't useless, these models are useful in answering questions pertaining to the aggregate economy. Incorporating heterogeneity allows us to answer questions on distributional impacts. In this introductory teach-in, we'll only cover methods for solving homogeneous-agent models, but I've left some useful resources at the end for further reading.


### Modelling infinite-horizon or finite-horizon
The final model consideration I'll talk about is whether to model households living indefinitely (over an infinite horizon), or whether they live for a finite amount of time. The infinite horizon assumption is often used for simplicity as infinite horizon models are stationary in nature - the remaining time horizon does not change as we move forward in time - and their characterization can therefore often be obtained more easily than when the time horizon changes over time. Furthermore, macroeconomic models with long time horizon show similar results to infinite-horizon models.

Nevertheless, there may be examples where modelling over a finite-horizon is more suitable. The overlapping generations model that Matt and I worked on is an example of a finite-horizon heterogeneous-agent model in discrete time.

I'll cover recursive methods for solving both infinite horizon and finite horizon problems, given that they are very similar.

### Aside Note
As an aside note, not all model assumptions have to be realistic for the model to be useful. Obviously in reality, we have finitely lived heterogeneous households in continuous time, but this doesn't mean that we can't get useful insights from models that violate these assumptions. There's a saying: "If you want a model of the real world, look out the window". Another solution I have is to impose an additional assumption that reality is not true.

---
# Deterministic Consumption-Saving Problem

Individual household chooses paths for consumption and saving at time $t$ to maximize the discounted sum of utilities
$$\max_{\{c_{\tau}, s_{\tau}\}_{\tau = t}^{\infty}} \sum_{\tau = t}^{\infty} \beta^{\tau - t} u(c_{\tau})$$
subject to the budget constraint for each $\tau \geq t$:
$$c_{\tau} + s_{\tau} \leq y_{\tau} + Rs_{\tau-1}$$
### Assumptions 
- $u'>0, u''<0, \lim_{c \to 0} u'(c) = \infty, \lim_{c \to \infty} u'(c) = 0$
- $s_{\tau} \geq 0$ for all $\tau \geq t$
- Constant interest rate $R > 0$
- Exogenous deterministic income stream $\{y_{\tau}\}_{\tau = t}^{\infty}$

We are interested in the equilibrium paths for $\left\{c_{\tau}, s_{\tau}\right\}_{\tau=t}^{\infty}$ that solve the household optimisation problem.

???
### Assumptions
- $u'>0, u''<0$ standard assumptions: utility is increasing but marginal utility is decreasing in consumption.
$\lim_{c \to 0} u'(c) = \infty, \lim_{c \to \infty} u'(c) = 0$ Inada conditions are also frequently assumed. The role of these conditions is to ensure the existence of an interior equilibrium. $\lim_{c \to 0} u'(c) = \infty$ implies that the first unit of consumption is infinitely beneficial to the household. $\lim_{c \to \infty} u'(c) = 0$ implies that the marginal utility from consumption is $0$ when consumption is infinite.

- Savings non-negative. No markets in this model; one-good economy in which the household can either consume or save (e.g. farmer and crops).

- Interest rate $R$ is assumed to be constant. In model with markets, interest rate is endogenously determined through market clearing conditions. No markets here.

- Exogenous deterministic income stream

This model is straightforward given there is no uncertainty. Household has a simple problem and must balance the trade-off between consumption and saving. If they consume more today, they have less savings tomorrow, which lowers future consumption. If they save more today, they have more consumption tomorrow but consume less today.

This maximisation problem can be solved in a number of ways, for example, by setting up an infinite-dimensional Lagrangian. But the most convenient and common way of approaching it is by solving recursively. The major advantage of using recursive methods to solve these problems is that it often gives better economic insights, similar to the logic of comparing today to tomorrow. I will go through a 6-step method to solve these problems recursively.

[Pause for questions on set-up of model]
---

# 1. Identifying control and state variables

.full-width[.content-box-blue[**Control variables** are variables that agents choose.]]
Control variables are usually easy to identify. In this example, the control variables are $c_t, s_t$.

.full-width[.content-box-blue[**State variables** are:
- Predetermined - the agent can observe the values for the state variables at time $t$ prior to making a decision.
- Relevant - the value of state variables affect the agent's choices and utility.
- Not redundant - the information the state variable contains cannot be summarized in a simpler way.
]]

State variables are more difficult to identify. In this example, there is an endogenous state variable $s_{t-1}$ and an exogenous state variable $y_{t}$.

---

# 2. Set-up the Bellman Equation
Define $V(s_{t-1}, y_{t})$ as the value of the above maximisation given the endogenous state $s_{t-1}$ and exogenous state $y_{t}$.

$$
\begin{align*}
    V(s_{t-1}, y_{t}) &= \max_{\{c_{\tau}, s_{\tau}\}_{\tau = t}^{\infty}} \sum_{\tau = t}^{\infty} \beta^{\tau-t} u(c_{\tau})  \\
    &= \max_{\{c_{\tau}, s_{\tau}\}_{\tau = t}^{\infty}} \left\{u(c_{t}) + \beta\sum_{\tau = t+1}^{\infty} \beta^{\tau - (t+1)} u(c_{\tau}) \right\} \\
    &= \max_{\{c_{t}, s_{t}\}} \left\{u(c_{t}) + \beta \max_{\{c_{\tau}, s_{\tau}\}_{\tau = t+1}^{\infty}} \left\{\sum_{\tau = t+1}^{\infty} \beta^{\tau - (t+1)} u(c_{\tau}) \right\}\right\} \\
    &= \max_{\{c_{t}, s_{t}\}} \left\{u(c_{t}) + \beta V(s_{t}, y_{t+1}) \right\}
\end{align*}
$$
where the maximisation is subject to the same date $t$ budget constraint.

???
### Introduction
Define $V(s_{t-1}, y_{t})$ as the value of the above maximisation given the endogenous state $s_{t-1}$ and exogenous state $y_{t}$. Note that the state variables are the arguments for the value function.

### Derivation
- Maximise present-discounted value of lifetime utility.
- Split summation into today's utility and future utility.
- Future utility is independent of today's utility, so we can separate the maximisation into maximising today and future utility.
- Nice property of infinite horizon models is that they are stationary; that is, after making a decision today, the problem tomorrow becomes the same as the problem today.

The Bellman equation is the value function subject to the budget constraint.

Useful to write the problem recursively as it simplifies the problem, since we only need to solve one Bellman equation.

---
# 3. Solving the Bellman Equation

There are two ways to solve the recursive problem. Either
- Substitute the budget constraint into the Bellman equation to remove one choice variable. Then solve by taking first-order conditions.
- Set-up a Lagrangian to solve the constrained maximisation problem

Using Lagrangian:
$$\mathcal{L} := u(c_{t}) + \beta V(s_{t}, y_{t+1}) + \lambda_{t}[y_{t} + Rs_{t-1} - c_{t} - s_{t}]$$

Take first order conditions with respect to control variables $c_{t}, s_{t}$:

$$
\begin{align}
    \frac{\partial \mathcal{L}}{\partial c_{t}}: \qquad & u'(c_{t}) - \lambda_{t} = 0 \label{eq:focc}\\
    \frac{\partial \mathcal{L}}{\partial s_{t}}: \qquad & \beta \frac{\partial V_{t+1}}{\partial s_{t}} - \lambda_{t} = 0 \label{eq:focs}
\end{align}
$$
Notation: $V_{t} = V(s_{t-1}, y_{t})$.

---
# 4. Envelope Conditions

Without proof:
$$\frac{\partial V_{t}}{\partial s_{t-1}} = \frac{\partial \mathcal{L}}{\partial s_{t-1}}$$

When taking the derivative of the objective function with respect to the state variable $s_{t-1}$, the state variable can be treated as an **independent variable** that will not affect the endogenous choice variables.

In this example,
$$\frac{\partial V_{t}}{\partial s_{t-1}} = \lambda_{t}R$$

which can be iterated forward one period to get: 

$$
\begin{equation}
\frac{\partial V_{t+1}}{\partial s_{t}} = \lambda_{t+1}R
\end{equation}
$$

???
Control variables are functions of state variables. However, envelope theorem allows us to treat the state variable as an **independent variable** that will not affect the endogenous choice variables. The intuition is that the indirect effects are 0 from the first order conditions with respect to the endogenous choice variables.

---
# 5. Collect terms
First, we can combine the envelope condition in equation ([3](#8)) with equation ([2](#7)) to get

$$\beta R \lambda_{t+1} - \lambda_{t} = 0$$
Combining equation ([1](#7)) with the above, we get the inter-temporal optimality condition for household consumption, otherwise known as the household Euler equation:

$$u'(c_{t}) = \beta R u'(c_{t+1})$$

???
The Euler equation has a nice economic interpretation: $u'(c_{t})$ is the marginal opportunity cost of investing in savings at time $t$. $\beta R u'(c_{t+1})$ is the marginal benefit of saving in time $t$.

---
# 6. Check
- Need equal number of linearly independent equations as unknown variables.

- There are 2 unknown variables in our example: $c_{t}, s_{t}$.

- We have 2 equations for household optimality: 

$$
\begin{align}
  u'(c_{t}) = \beta R u'(c_{t+1}) \tag{E1} \\
  c_{t} + s_{t} = y_{t} + Rs_{t-1} \tag{E2} \\
  \lim_{T \to \infty} \beta^{T} u'(c_{T}) s_{T-1} = 0 \tag{TVC}
\end{align}
$$


An equilibrium of the economy is given by the paths for $\left\{c_{\tau}, s_{\tau}\right\}_{\tau=t}^{\infty}$ with $s_{t-1}$ given, such that the conditions from the household maximisation problem are satisfied. 

Given a specific utility function and parameter values for $\beta$ and  $R$, the path for consumption and savings $\left\{c_{\tau}, s_{\tau}\right\}_{\tau=t}^{\infty}$ can be numerically estimated on a computer.

???
### Equilibrium
If you did everything correctly, you should have an equal number of linearly independent equations as unknown variables, for identification.

The unknown variables in our example are the same as our control variables $c_{t}, s_{t}$.

We have two equations from the household's optimality conditions: the inter-temporal optimality condition for consumption and also the household budget constraint. The inter-temporal optimality condition for consumption is a difference equation, so we need two additional boundary conditions to pin down the levels for consumption: $s_{t-1}$ being given gives an upper bound for $c_{t}$. The transversality condition plays the role of a terminal boundary condition.

### Transversality condition:
The intuition for the transversality condition is that an optimality condition and must be satisfied in order for the individual to maximize its inter-temporal utility, by preventing an over-accumulation of savings. 

The transversality condition can be given this interpretation: $Ru'(c_{T})$ is the marginal benefit of an additional inherited unit of savings at date $T$. $Ru'(c_{T}) s_{T-1}$ is the total value of inherited savings at date $T$. Just as the expected present value of last-period savings in the finite-horizon version of this problem must be 0, the expected present value of savings in the infinite horizon must also be 0.

### Numerical Estimation:
There are many methods - the simplest being Value Function Iteration. The algorithms for solving these models are outside the scope of this course. See Ben Moll's lecture notes for further reading.

---
# Summary
We used the 6-step process to solve the representative household's maximisation problem and found the equilibrium conditions that characterize the paths for consumption and savings.
1. Identifying control and state variables

2. Set-up the Bellman Equation

3. Solve the Bellman Equation

4. Envelope Conditions

5. Collect terms

6. Check

---
# Deterministic Consumption-Saving - Finite Horizon

Individual household chooses paths for consumption and saving at time $t$ to maximize the discounted sum of utilities
$$\max_{\{c_{\tau}, s_{\tau}\}_{\tau = t}^{T}} \sum_{\tau = t}^{T} \beta^{\tau - t} u(c_{\tau})$$
subject to the budget constraint for each $t \leq \tau \leq T$:
$$c_{\tau} + s_{\tau} \leq y_{\tau} + Rs_{\tau-1}$$
### Assumptions 
- $u'>0, u''<0, \lim_{c \to 0} u'(c) = \infty, \lim_{c \to \infty} u'(c) = 0$
- $s_{\tau} \geq 0$ for all $\tau \geq t$
- Constant interest rate $R$
- Exogenous deterministic income stream $\{y_{\tau}\}_{\tau = t}^{T}$

We are interested in the equilibrium paths for $\left\{c_{\tau}, s_{\tau}\right\}_{\tau=t}^{T}$ that solve the household optimization problem.

---
# Finite horizon dynamic programming

- Value function depends on time $\tau$.

- Backward iteration starting at $\tau = T$
$$
\begin{align*}
& V_{T}(s_{T-1}, y_{T}) = \max_{\{c_{T}, s_{T}\}} u(c_{T}) \qquad \text{subject to} \\
& c_{T} + s_{T} \leq y_{T} + Rs_{T-1} \\
& s_{T} \geq 0
\end{align*}
$$
- Solution is to consume all wealth in final period
$$
\begin{align*}
c_{T} &= y_{T} + Rs_{T-1} \\
s_{T} &= 0 \\
V_{T}(s_{T-1}, y_{T}) &= u(y_{T} + Rs_{T-1})
\end{align*}
$$

- Solve same Bellman equation as in infinite-horizon problem:
$$
\begin{align*}
& V_{t}(s_{t-1}, y_{t}) = \max_{\{c_{t}, s_{t}\}} u(c_{t}) + \beta V_{t+1}(s_{t}, y_{t+1}) \qquad \text{subject to} \\
& c_{t} + s_{t} \leq y_{t} + Rs_{t-1} \\
& s_{t} \geq 0 \\
\end{align*}
$$

---
# A more complicated example
Consider a competitive closed economy in which the representative household chooses the rule of consumption, labor and stock holdings ${c_t, n_t, a_t}$ in order to maximize the expected discounted utility:
$$\mathbb{E}_{t}\left\{\sum_{\tau=t}^{\infty}\beta^{\tau-t}\left[2(c_{\tau})^{\frac{1}{2}}-n_{\tau}\right]\right\}$$
subject to the budget constraint:
$$c_{t}+p_{t} a_{t}=w_{t} n_{t}+\left(d_{t}+p_{t}\right) a_{t-1}$$
where $w_{t}$ is real wage rate, $d_{t}$ is dividend and $p_{t}$ is ex-dividend price of the stock, and $\mathbb{E}_{t}\{\cdot\}$ is expected value of conditional on information at date $t$.

There is also a representative firm which maximizes the profit (=dividend) $d_{t} = y_{t} - w_{t} n_{t}$ subject to the production function,
$y_{t}=A_{t} n_{t}{ }^{\alpha}$ where $0<\alpha<1$

The aggregate productivity $A_{t}$ is either high at $A^{H}$ or low at $A^{L}$, and follows a Markov process as:

$$\mathbb{P}\left(A_{t+1}=A^{H} \mid A_{t}=A^{H}\right) = \mathbb{P}\left(A_{t+1}=A^{L} \mid A_{t}=A^{L}\right)=\gamma >\frac{1}{2}$$

The supply of shares is normalized to be one per households, and the market clearing condition is given by $a_{t} = 1$ and $y_{t} = c_{t}$.

- Derive the conditions of the competitive equilibrium of this economy.

???
The *representative household* assumption means that all households' preferences are identical. That is, preferences can be represented as if a single household made the aggregate consumption and saving decisions subject to a single budget constraint.

A **markov process** $A_{t}$ is a stochastic process in which the distribution of $A_{t}$ conditional on the whole history of past realizations of $A^{t-1}$ is a function of only the most recent realization $A_{t}$. This assumption is useful as it allows us to write the maximisation problem recursively as seen before.

A **competitive equilibrium** is an allocation $\left\{c_{\tau}, n_{\tau}, a_{\tau}, d_{\tau}, y_{\tau}\right\}_{\tau = t}^{\infty}$ with prices $\left\{p_{\tau}, w_{\tau} \right\}_{\tau = t}^{\infty}$ such that the allocation solves the household and firm's maximisation problem and the allocation is feasible.

---
# 1. Identify control and state variables

The control variables are: ${c_t, n_t, a_t}$.

The state variables are: $a_{t-1}, A_{t}$.

- In general, *prices* are **not** state variables, because they are not predetermined.

???
In general, *prices* are **not** state variables, because they are not predetermined, but rather determined in a rational expectations equilibrium. Households can calculate their optimal decision as a function of prices, and then prices are determined through market clearing conditions. While prices are not observable at time $t$, the assumption that households are rational means that they are able to form expectations on prices. Therefore, $p_{t}, w_{t}$ are not state variables.

---
# 2. Set-up the Bellman Equation

Define $V(a_{t-1}, A_{t})$ as the value of the above maximisation given the endogenous state $a_{t-1}$ and exogenous state $A_{t}$.

$$
\begin{align*}
    V(a_{t-1}, A_{t}) &= \max_{\{c_{\tau}, s_{\tau}\}_{\tau = t}^{\infty}} \mathbb{E}_{t}\left[\sum_{\tau = t}^{\infty} \beta^{\tau-t} u(c_{\tau}, n_{\tau})\right]  \\
    &= \max_{\{c_{\tau}, s_{\tau}\}_{\tau = t}^{\infty}} \left\{u(c_{t}, n_{t}) + \beta \mathbb{E}_{t}\left[\sum_{\tau = t+1}^{\infty} \beta^{\tau - (t+1)} u(c_{\tau}, n_{\tau})\right] \right\} \\
    \textit{(Tower rule)} &= \max_{\{c_{\tau}, s_{\tau}\}_{\tau = t}^{\infty}} \left\{u(c_{t}, n_{t}) + \beta \mathbb{E}_{t}\left[\mathbb{E}_{t+1}\left[\sum_{\tau = t+1}^{\infty} \beta^{\tau - (t+1)} u(c_{\tau}, n_{\tau})\right]\right] \right\} \\
    &= \max_{\{c_{t}, s_{t}\}} \left\{u(c_{t}, n_{t}) + \beta \mathbb{E}_{t}\left[\max_{\{c_{\tau}, s_{\tau}\}_{\tau = t+1}^{\infty}} \mathbb{E}_{t+1}\left[\sum_{\tau = t+1}^{\infty} \beta^{\tau - (t+1)} u(c_{\tau}, n_{\tau})\right]\right] \right\} \\
    &= \max_{\{c_{t}, s_{t}\}} \left\{u(c_{t}, n_{t}) + \beta\mathbb{E}_{t}[V(a_{t}, A_{t+1})] \right\}
\end{align*}
$$
where the maximisation is subject to the same date $t$ budget constraint.

---
# 3. Solving the Bellman Equation
The Lagrangian for the representative household's maximisation problem is:

$$\mathcal{L} := 2(c_{t})^{\frac{1}{2}}-n_{t} + \beta \mathbb{E}_{t}[V(a_{t}, A_{t+1})] + \lambda_{t}[w_{t}n_{t} + (d_{t} + p_{t})a_{t-1} - c_{t} - p_{t}a_{t}]$$

Take first order conditions:

$$
\begin{align}
  \frac{\partial \mathcal{L}}{\partial c_{t}}: \qquad & (c_{t})^{-\frac{1}{2}} - \lambda_{t} = 0 \label{eq:focc2} \\
  \frac{\partial \mathcal{L}}{\partial n_{t}}: \qquad & -1 + \lambda_{t}w_{t} = 0 \label{eq:focn2} \\
  \frac{\partial \mathcal{L}}{\partial a_{t}}: \qquad & \beta \mathbb{E}_{t} \left[\frac{\partial V_{t+1}}{\partial a_{t}}\right] - \lambda_{t}p_{t} = 0 \label{eq:foca2} \\
\end{align}
$$
---
# 4. Envelope Conditions

Recall that the envelope condition states that:
$$\frac{\partial V_{t}}{\partial a_{t-1}} = \frac{\partial \mathcal{L}_{t}}{\partial a_{t-1}}$$

Therefore,
$$\frac{\partial V_{t}}{\partial a_{t-1}} = \lambda_{t}(d_{t} + p_{t})$$

which can be iterated forward one period to get: 

$$\begin{equation}\label{eq:envelope2}
    \frac{\partial V_{t+1}}{\partial a_{t}} = \lambda_{t+1}(d_{t+1} + p_{t+1}) 
\end{equation}$$

---
# 5. Collect terms
First, we can combine the envelope condition in equation ([7](#18)) with equation ([6](#17)) to get:
$$\beta \mathbb{E}_{t} [\lambda_{t+1}(d_{t+1} + p_{t+1})] - \lambda_{t}p_{t} = 0$$
Combining equation ([4](#17)) with the above, we get the household Euler equation:
$$\beta \mathbb{E}_{t} \left[\frac{d_{t+1} + p_{t+1}}{\sqrt{c_{t+1}}}\right] = \frac{p_{t}}{\sqrt{c_{t}}}$$

Combining equations ([4](#17)) and ([5](#17)), we get:
$$\sqrt{c_{t}} = w_{t}$$

---
# Firm maximisation problem

The firm has a static maximisation problem:
$$\max_{\{n_{t}\}} A_{t}n_{t}^{\alpha}-w_{t}n_{t}$$

First Order Condition:
$$\alpha A_{t}n_{t}^{\alpha-1}-w_{t} = 0$$

---
# 6. Check

We have 7 unknown variables in our example: $c_{t}, n_{t}, a_{t}, p_{t}, d_{t}, w_{t}, y_{t}$.

For identification, we need 7 linearly independent equations.

$$
\begin{align}
    & \beta \mathbb{E}_{t} \left[\frac{d_{t+1} + p_{t+1}}{\sqrt{c_{t+1}}}\right] = \frac{p_{t}}{\sqrt{c_{t}}} \tag{CE1} \\
    & \sqrt{c_{t}} = w_{t} \tag{CE2} \\
    & \alpha A_{t}n_{t}^{\alpha-1}-w_{t} = 0 \tag{CE3} \\
    & c_{t}+p_{t} a_{t}=w_{t} n_{t}+\left(d_{t}+p_{t}\right) a_{t-1} \tag{CE4} \\
    & y_{t} = A_{t}n_{t}^{\alpha} \tag{CE5} \\
    & d_{t} = y_{t} - w_{t}n_{t} \tag{CE6} \\
    & a_{t} = 1 \tag{CE7} \\
    & \lim_{T \to \infty} \beta^{T} \mathbb{E}_{t}\left[\frac{d_{T} + p_{T}}{\sqrt{c_{T}}}a_{T-1} \right] = 0 \tag{TVC}
\end{align}
$$

A competitive equilibrium of the economy is given by the stochastic processes for $\{c_{\tau}, n_{\tau}, a_{\tau}, p_{\tau}, d_{\tau}, w_{\tau}, y_{\tau}\}_{\tau=t}^{\infty}$ with $a_{t-1}$ given, such that all stochastic processes satisfy the conditions from household and firm optimisation, and market clearing conditions given by the above 7 equations plus the transversality condition.

???
### Identification
- We have 2 equations from the household's maximisation problem, 1 equation from the firm's maximisation problem, 3 resource constraints, 1 market clearing condition and finally a transversality condition:

### Walras' Law
Note that while we had 2 market clearing conditions: $y_{t} = c_{t}$ and $a_{t} = 1$, we only need to include one market clearing condition. This is because of *Walras' law* which states that if households preferences are monotonic and all but one markets clear, then it must be true that all markets clear. You can convince yourself that the market clearing condition for goods, $y_{t} = c_{t}$ is implied by the system of equations above (specifically equations (4), (6) and (7)).

### Transversality Condition
- The transversality condition has a similar interpretation to before. $\frac{d_{T} + p_{T}}{\sqrt{c_{T}}}$ is the marginal benefit of an additional inherited unit of stock holdings at date $T$. $\frac{d_{T} + p_{T}}{\sqrt{c_{T}}}a_{T-1}$ is the total value of inherited stock holdings at date $T$. The transversality condition implies that the expected present value of stock holdings in the infinite horizon must be 0.

### Model interpretation
- Why do we care about a model like this? The model helps to explain whether macro variables are pro-cyclical or counter-cyclical, given that there is variation in aggregate productivity. For example, suppose there's an increase in aggregate productivity, from $A_{t}^{L}$ to $A_{t}^{H}$. Solving the model with pen and paper or numerically, you can show that output, consumption, wages, labour supply and stock prices are pro-cyclical, whereas the price-dividend ratio and the risk-free interest rate is counter-cyclical. (*Intuitively, expected productivity growth is lower when productivity today is higher (because then productivity can only remain constant or decline), so consumption is expected to be scarcer tomorrow relative to today, and therefore the risk-free interest rate is lower.*)

---
# Useful Resources
### Lecture Notes:
- Per Krussel's Macroeconomics lecture notes http://www.econ.yale.edu/smith/econ510a/book.pdf
- Ben Moll's Macroeconomic Theory 1, Princeton, 2014 1st Year PhD lecture notes. https://benjaminmoll.com/lectures/

### More advanced textbooks:
- Acemoglu, Daron. 2007. "Introduction to Modern Economic Growth." Princeton University Press.
- Ljungqvist, Lars & Sargent, Thomas J., 2012. "Recursive Macroeconomic Theory, Third Edition." The MIT Press.
- Stachurski, John. 2009. "Economic Dynamics." The MIT Press.
- Stokey, Nancy L., et al. 1989. "Recursive Methods in Economic Dynamics." Harvard University Press.

???
- Per Krussel: General background
- Ben Moll: Modelling in continuous time, with heterogeneous households, notes on numerical approximation with codes.
- Textbooks give more rigorous treatment. Most self-contained but maths more complicated; in particular knowledge of real analysis and measure theory is useful. Stokey, Lucas with Prescott gives the most complete treatment of discounted stationary dynamic programming problems - but does require some familiarity with real analysis and measure theory, so I recommend to check Acemoglu's book first.

---
# Practice
.panelset[
.panel[.panel-name[Problem]
Consider the Brock-Mirman optimal growth model with stochastic shocks. The social planner chooses the paths for consumption and capital to maximise 
$$\mathbb{E}_{t}\left\{\sum_{\tau=t}^{\infty}\beta^{\tau-t} \ln{c_{\tau}} \right\}$$
subject to 
$$c_{t} + k_{t+1} \leq Ak_{t}^{\alpha}\theta_{t}$$ 
$k_{t}$ given, $A > 0, 0 < \alpha < 1$, where $\{\theta_{t}\}$ is an i.i.d. sequence with $\ln{\theta_{t}}$ distributed $\mathcal{N}(0, \sigma^2)$.

- Derive the conditions of the equilibrium of this economy.
]

.panel[.panel-name[Solution]
The equilibrium is characterised by sequences $\{c_{\tau}, k_{\tau+1}\}_{\tau=t}^{\infty}$ that satisfy:

$$
\begin{align}
    & 1 = \mathbb{E}_{t}\left[\beta \frac{c_{t}}{c_{t+1}} A \alpha k_{t+1}^{\alpha-1}\theta_{t+1}\right] \tag{E1} \\
    & c_{t} + k_{t+1} = Ak_{t}^{\alpha}\theta_{t} \tag{E2} \\
    & \lim_{T \to \infty} \beta^{T} \mathbb{E}_{t}\left[\frac{ k_{T}^{\alpha}\theta_{T}}{c_{T}}\right] = 0 \tag{TVC}
\end{align}
$$
]
]


